pod 'MBProgressHUD', '~> 0.9.1'
pod 'Reachability', '~> 3.2'
pod 'BmobSDK', '~> 1.6.3'
pod 'SDWebImage', '~> 3.7.3'
pod 'EaseMobSDK'
pod 'RegexKitLite'
pod 'SMS-For-iOS'
pod 'JVFloatingDrawer'
pod 'JTSlideShadowAnimation'